version: 2.1

# Defining Jobs for Hello World
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - run: ruby hello-world.rb
  test:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - run: ruby hello-world.rb

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
